config/routes.rb
Rails.application.routes.draw do
  root to: 'trips#index'

  get    '/register', to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get    '/logout',   to: 'sessions#destroy'
  get    '/tags',     to: 'tags#index'

  resources :trips, except: [:destroy] do
    resources :posts, except: [:index] do
      resources :comments, only: [:create]

      get 'star', to: 'posts#star'
      get 'like', to: 'posts#like'
    end

    get 'activities', to: 'activities#index'
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr/>
</p>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="alert alert-danger span8">
      <h5>There were some errors: </h5>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_star.html.erb
<% if post.status == 'active' %>
  <%= link_to trip_post_star_path(@trip, post) do  %>
    <i class='glyphicon glyphicon-star like'></i>
  <% end %>
<% else %>
  <%= link_to trip_post_star_path(@trip, post) do  %>
    <i class='glyphicon glyphicon-star-empty like'></i>
  <% end %>
<% end %>

app/views/shared/_tags.html.erb
<% tags.each do |tag| %>
  <span class='badge'><%= link_to tag.name, trip_path(trip, tag: tag.name) %></span>
<% end %>

app/views/shared/like.js.erb
$('#likes_count_<%= object.slug%>').html('<%= object.likers.size %>');

<% if object.likers.include?(current_user) %>
  $('#like_<%= object.slug%>').html('Unlike');
<% else %>
  $('#like_<%= object.slug%>').html('<span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Like');
<% end %>