config/routes.rb
Rails.application.routes.draw do
  root to: 'trips#index'

  get    '/register', to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get    '/logout',   to: 'sessions#destroy'
  get    '/tags',     to: 'tags#index'

  resources :trips, except: [:destroy] do
    resources :posts, except: [:index] do
      resources :comments, only: [:create]

      get 'star', to: 'posts#star'
      get 'like', to: 'posts#like'
    end

    get 'activities', to: 'activities#index'
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Sluggable
  include PublicActivity::Common
  acts_as_taggable_on :tags
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :trip
  has_many :comments
  has_many :likes
  has_many :likers, through: :likes

  mount_uploader :picture, PictureUploader
  sluggable_column :title

  NEW_POST_TITLE = 'New Post'

  def self.new_post
    post = Post.new(title: NEW_POST_TITLE, start_date: Date.current, end_date: Date.current)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_trip
  before_action :require_login_as_trip_member
  before_action :set_post, only:[:edit, :update, :show, :destroy]
  before_action :set_tag_autocomplete, only:[:new, :edit]
  before_action :require_creator, only:[:edit, :update]

  def new
    @post = @trip.posts.build
    @post.start_date = @trip.start_date
    @post.end_date   = @trip.end_date
  end

  def create
    @post = @trip.posts.build(post_params)
    @post.creator = current_user

    if @post.save
      @post.tag_ids = []
      @trip.tag(@post, with: params[:post][:tag_list], on: :tags)

      @post.create_activity :create, owner: current_user, recipient: @trip
      flash[:notice] = 'Your post was added'
      redirect_to @trip
    else
      render 'new'
    end
  end

  def star
    post = Post.find_by(slug: params[:post_id])
    if post.status == 'active'
      post.status = nil
    else
      post.status = 'active'
    end
    post.save

    redirect_to :back
  end

  def like
    post = Post.find_by(slug: params[:post_id])
    if post.likers.include?(current_user)
      post.likers.delete(current_user)

      post.create_activity :unlike, owner: current_user, recipient: @trip
    else
      post.create_activity :like, owner: current_user, recipient: @trip
      post.likers.push(current_user)
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'shared/like', :locals => { object: post} }
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    if @post.save
      @post.tag_list = []
      @trip.tag(@post, with: params[:post][:tag_list], on: :tags)
      @post.create_activity :update, owner: current_user, recipient: @trip
      flash[:notice] = "Post was updated"
      redirect_to trip_post_path(@trip, @post)
    else
      render 'edit'
    end
  end

  def show
    @comment = Comment.new
  end

  def destroy
    @post.create_activity :destroy, owner: current_user, recipient: @trip
    @post.delete
    flash[:notice] = "Post was deleted"
    redirect_to @trip
  end

  private
    def set_trip
      @trip = Trip.find_by(slug: params[:trip_id])
    end

    def require_login_as_trip_member
      if !@trip.users.include?(current_user) || !logged_in?
        flash[:error] = 'You are not trip member'
        redirect_to root_path
      end
    end

    def set_post
      @post = Post.find_by(slug: params[:id])
    end

    def set_tag_autocomplete
      @autocomplete_items = @trip.owned_tags
    end

    def post_params
      params.require(:post).permit(:title, :description, :start_date, :end_date, :picture)
    end

    def require_creator
      if @post.creator != current_user
        flash[:error] = "You can't do that!"
        redirect_to @trip
      end
    end
end

app/views/posts/_form.html.erb
<%= render 'shared/error_message', object: @post %>

<div class="container">
  <div class="row">
    <%= form_for([@trip, @post], html: { multipart: true }) do |f| %>
      <div class="col-md-5">
        <div class='form-group'>
          <%= f.label :title %>
          <%= f.text_field :title, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class:'form-control'%>
        </div>
        <div class='form-group'>
          <%= f.label :start_date %>
          <%= f.date_field :start_date, class:'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :end_date %>
          <%= f.date_field :end_date, class:'form-control' %>
        </div>
        <div class='input-row'>
          <%= f.hidden_field :tag_list, autocomplete:"off" %>
          <%= text_field_tag 'tag_input', nil, class: "tm-input", placeholder: "Tags", autocomplete:"on" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class='form-group'>
          <%= f.label :picture %>
          <% if @post.picture? %>
            <%= image_tag @post.picture.url %>
          <% else %>
            <%= image_tag '/NoImage.jpg' %>
          <% end %>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
        </div>
        <br/>
        <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post' , class: 'btn btn-primary') %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_tag "var items = #{ @post.tags_from(@trip).to_json };" %>
<%= javascript_tag "var autocomplete_items = #{ @autocomplete_items.to_json(:only => :name) };" %>
<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

  var tags = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: autocomplete_items
    });

    tags.initialize();

    var tagApi = jQuery(".tm-input").tagsManager({
      prefilled: items,
      hiddenTagListName: 'post[tag_list]',
      hiddenTagListId: 'post_tag_list',
    });
    jQuery(".tm-input").typeahead(null, {
      name: 'tags',
      displayKey: 'name',
      source: tags.ttAdapter()
    }).on('typeahead:selected', function (e, d) {
        tagApi.tagsManager("pushTag", d.name);
    });

</script>

app/views/posts/_post.html.erb
<div class="box panel panel-default">
  <div class="show-image">
    <%= link_to show_or_create_post(@trip, post) do %>
      <% if post.picture? %>
        <%= image_tag post.picture.url %>
      <% else %>
        <%= image_tag '/NoImage.jpg' %>
      <% end %>
    <% end %>
    <% if post.title != Post::NEW_POST_TITLE %>
      <div class="btn-group like" role="group" aria-label="...">
        <%= link_to trip_post_like_path(@trip, post), remote: true, class:"btn btn-default" do %>
          <div id="like_<%= post.slug %>">
            <% if post.likers.include?(current_user) %>
              Unlike
            <% else %>
              <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Like
            <% end %>
          </div>
        <% end %>
        <button type="button" id="likes" class="btn btn-default">
          <div id="likes_count_<%= post.slug %>"><%= post.likers.size %></div>
        </button>
      </div>
    <% end %>
  </div>
  <div class="title">
    <h2>
      <%= link_to post.title, show_or_create_post(@trip, post) %>
    </h2>
  </div>

  <div class="period">
    <i class="glyphicon glyphicon-time"></i>
    <%= show_period(post) %>
  </div>
  <div class="taglist">
    <%= render 'shared/tags', tags: post.tags, trip: @trip %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>

<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if current_user == @post.creator %>
  <p class="pull-right">
    <%= link_to edit_trip_post_path(@trip, @post) do %>
      <i class="glyphicon glyphicon-pencil"></i>
      Edit This Post
    <% end %>
     |
    <%= link_to trip_post_path(@trip, @post), method: :delete, data: { confirm: "You sure?" } do %>
      <i class="glyphicon glyphicon-trash"></i>
      Delete This Post
    <% end %>
  </p>
<% end %>
<%= render 'shared/content_title', title: @post.title %>
<%= render 'shared/tags', tags: @post.tags, trip: @trip %>
<hr/>

<div class="row">
  <div class="col-md-8 ">
    <%= image_tag(@post.picture, class:"img-rounded img-responsive" )%>

    <p class="description">
      <%= simple_format(@post.description) %>
    </p>
    <hr/>
    <p>
      <strong>
        Posted by <%= @post.creator.username %>
      </strong>
    </p>

    <hr/>

    <%= render @post.reload.comments , show_post: false %>
    <% if logged_in? %>
      <%= form_for [@trip, @post, @comment] do |f| %>
        <%= render 'shared/error_message', object: @comment %>
        <div class="form-group">
          <%= f.text_area :body , rows: 3, class: 'form-control span4', placeholder: 'Add a comment...' %>
        </div>
        <%= f.submit 'Create comment' , class:"btn btn-primary" %>
      <% end %>
    <% end %>
  </div>

</div>