config/routes.rb
Rails.application.routes.draw do
  root to: 'trips#index'

  get    '/register', to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  get    '/logout',   to: 'sessions#destroy'
  get    '/tags',     to: 'tags#index'

  resources :trips, except: [:destroy] do
    resources :posts, except: [:index] do
      resources :comments, only: [:create]

      get 'star', to: 'posts#star'
      get 'like', to: 'posts#like'
    end

    get 'activities', to: 'activities#index'
  end

  resources :users, only: [:show, :create, :edit, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Let's go!", root_path, class:'navbar-brand'  %>
<div class="container-fluid">
  <div id="navbar" class="navbar-collapse collapse ">
    <ul class="nav navbar-nav">
      <%= render 'layouts/trip_menu' %>
      <% if @trip && !@trip.new_record? %>
        <li>
          <%= link_to @trip.name, trip_path(@trip), id: "trip_name" %>
        </li>
        <li>
          <%= link_to new_trip_post_path(@trip) do %>
            <i class="glyphicon glyphicon-plus"></i>
            New Post
          <% end %>
        </li>
        <%= render 'layouts/select_date', trip: @trip %>
        <li><%= link_to 'Activities', trip_activities_path(@trip) %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if @trip && !@trip.new_record? && (@trip.creator == current_user) %>
        <li>
          <%= link_to edit_trip_path(@trip) do %>
            <i class="glyphicon glyphicon-pencil"></i>
            Edit This Trip
          <% end %>
        </li>
      <% end %>
      <%= render 'layouts/user_menu' %>
    </ul>
  </div>
</div>

app/views/layouts/_select_date.html.erb
<li class="pull-left dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <%= params[:date] ? params[:date] : "Select Date" %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'none', trip_path(trip) %></li>
    <% trip.start_date.upto(trip.end_date).each do |date| %>
      <li><%= link_to format_date(date), trip_path(@trip, date: date) %></li>
    <% end %>
  </ul>
</li>

app/views/layouts/_trip_menu.html.erb
<li class='dropdown'>
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <i class="glyphicon glyphicon-plane"></i>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <% if logged_in? %>
      <% current_user.trips.each do |trip| %>
        <li><%= link_to trip.name, trip %></li>
      <% end %>
    <% end %>
    <li class="divider"></li>
    <li>
      <%= link_to(new_trip_path) do%>
        <i class='icon-plus'></i>
        New Trip
      <% end %>
    </li>
  </ul>
</li>

app/views/layouts/_user_menu.html.erb
<% if logged_in? %>
  <li class='dropdown'>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <%= current_user.username %>
      <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to(edit_user_path(current_user)) do%>
          <i class='glyphicon glyphicon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to(current_user) do%>
          <i class='glyphicon glyphicon-user'></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to(logout_path) do%>
          <i class='glyphicon glyphicon-circle-arrow-left'></i>
          logout
        <% end %>
      </li>
    </ul>
  </li>
<% else %>
  <li>
    <%= link_to 'Login', login_path %>
  </li>
  <li>
    <%= link_to 'Register', register_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Let's go!</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>